site_name: Tesk MkDocs
site_description: Demo-Dokumentation mit MkDocs
site_author: haenno
# Optional: passe die URL an, sobald Pages konfiguriert ist
site_url: https://haenno.github.io/tesk_mkdocs/

# Inhalte liegen nun im Repository-Root
docs_dir: .

# Verhindert Probleme mit Pfaden auf Project Pages (Nutze .html statt /-Verzeichnisse)
use_directory_urls: false

# Baue das Site-Output außerhalb des Docs-Verzeichnisses (da docs_dir='.')
site_dir: ../site

nav:
  - Start: index.md
  - Anleitung: anleitung.md
  - README: readme.md

theme:
  name: material
  language: de
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - attr_list
