name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Passe ggf. den Branch-Namen an
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-to-pdf

      - name: Build site + PDF
        run: ENABLE_PDF_EXPORT=1 mkdocs build --config-file mkdocs.yml

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../site

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-pdf
          path: ../site/pdf/document.pdf

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
